### ISSUE TITLE
Fabric comparison

### ISSUE THREAD

**Issue by gageorsburn** [napalm-automation/brigade#16]
Is there any notable difference between this and fabric?

**Comment by dbarrosop** [comment]
I am sure there are way more as I know very little about fabric but main differences are:

1. `fab` deals with hosts and groups of hosts (without data). `brigade` deals with collections of data.
2. `fab` takes care of running commands on remote hosts. `brigade` takes care of multiplexing tasks amongst collections of data. What the task does, is up to you.
3. `fab` is a CLI tool. `brigade` is a framework so you can build your own tools
two differences are that `fab` doesn't deal with data and it's a CLI tool while `brigade` manages and present

We call these collections of data "hosts" because I guess that is the main use case but if could be anything to be honest. It could be your collection of movies/music for that matter as tasks are not limited/focused around running commands. The main idea is to define tasks and have brigade multiplex that task making sure each execution of the task has the data relevant for that host. For instance:

```
my_movies.yaml
-----------------
movie_a:
    director: [blah]
    year: 1999
    actors: [a, b, c, d]
movie_b:
    director: [blah]
    year: 1999
    actors: [a, b, c, d]
```

A task could be:

```
def insert_into_db(task):
    sqlalchemy.insert(table="movies", values=(task.host.name, task.host["director"], task.host["year"]...))
```

Again, no expert on fabric but I hope this answer covered your question.
